package net.slidesoft.wavesbistro;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import net.slidesoft.wavesbistro.dialogs.NewCategoryDialog;

/**
 *
 * @author Rachid El Alaoui , SlideSoft.net
 */
public class TableContentDialog extends javax.swing.JDialog {

    private final ProductTableModel productModel ;
    private final String title ;    
    
    /**
     * Creates new form TableContentDialog
     */
    public TableContentDialog(java.awt.Frame parent, String titl, ProductTableModel model) {
        super(parent, titl,true);
        this.title = titl ;
        initComponents();
        lblTable.setText(titl);
        lblTable1.setText( Utils.now() + ", " +  titl);
        productModel = model ;
        JTableHeader header = productTable.getTableHeader();
        header.setFont(new Font("Dialog", Font.BOLD, 18));
        productTable.setModel(productModel);
        productTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        productTable.getColumnModel().getColumn(1).setPreferredWidth(180);
        productTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        productTable.getColumnModel().getColumn(3).setPreferredWidth(30);
        catList.setModel( CatListModel.get() );
        
        NewCategoryDialog.get(this).setAddCategoryListener( new AddCatListener() {
            @Override
            public void add(String cat) {
                CategoryDB.get().addCat( new Category(cat) );
            }
        } );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        lblTable = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        splitter = new javax.swing.JSplitPane();
        pnlProducts = new javax.swing.JPanel();
        pnlCategories = new javax.swing.JPanel();
        btnAddCategory = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        catList = new javax.swing.JList<>();
        pnlCategoryProducts = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnIncByOne = new javax.swing.JButton();
        btnClearProductsFromTable = new javax.swing.JButton();
        btnDecByOne = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        totalLbl = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        edtCash = new javax.swing.JTextField();
        cashLbl = new javax.swing.JLabel();
        balanceLBl = new javax.swing.JLabel();
        lblRetour = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pnlBottom = new javax.swing.JPanel();
        btnClose1 = new javax.swing.JButton();
        lblTable1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlTop.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pnlTop.setPreferredSize(new java.awt.Dimension(1178, 80));

        btnClose.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblTable.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblTable.setText("Table");
        lblTable.setOpaque(true);

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTable, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 714, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(lblTable))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlMain.setLayout(new java.awt.BorderLayout());

        splitter.setDividerLocation(400);

        pnlProducts.setLayout(new java.awt.BorderLayout());

        pnlCategories.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCategories.setPreferredSize(new java.awt.Dimension(200, 200));
        pnlCategories.setLayout(new java.awt.BorderLayout());

        btnAddCategory.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAddCategory.setText("+ Category");
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });
        pnlCategories.add(btnAddCategory, java.awt.BorderLayout.PAGE_START);

        btnAddProduct.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAddProduct.setText("+ Product");
        pnlCategories.add(btnAddProduct, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 130));

        catList.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        catList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        catList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                catListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(catList);

        pnlCategories.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnlProducts.add(pnlCategories, java.awt.BorderLayout.LINE_END);

        pnlCategoryProducts.setLayout(new java.awt.GridLayout(3, 2, 10, 10));
        pnlProducts.add(pnlCategoryProducts, java.awt.BorderLayout.CENTER);

        splitter.setRightComponent(pnlProducts);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        productTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productTable.setRowHeight(30);
        jScrollPane1.setViewportView(productTable);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        btnIncByOne.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnIncByOne.setText("Plus");
        btnIncByOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncByOneActionPerformed(evt);
            }
        });
        jPanel5.add(btnIncByOne);

        btnClearProductsFromTable.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnClearProductsFromTable.setText("Clear");
        btnClearProductsFromTable.setMinimumSize(new java.awt.Dimension(85, 42));
        btnClearProductsFromTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearProductsFromTableActionPerformed(evt);
            }
        });
        jPanel5.add(btnClearProductsFromTable);

        btnDecByOne.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnDecByOne.setText("Minus");
        btnDecByOne.setMinimumSize(new java.awt.Dimension(85, 42));
        btnDecByOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecByOneActionPerformed(evt);
            }
        });
        jPanel5.add(btnDecByOne);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        totalLbl.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        totalLbl.setForeground(new java.awt.Color(255, 255, 255));
        totalLbl.setText("Total DH :");

        lblTotal.setBackground(new java.awt.Color(0, 0, 0));
        lblTotal.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("00");

        edtCash.setBackground(new java.awt.Color(0, 0, 0));
        edtCash.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        edtCash.setForeground(new java.awt.Color(255, 255, 255));
        edtCash.setText("50.00");
        edtCash.setPreferredSize(new java.awt.Dimension(4, 43));

        cashLbl.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        cashLbl.setForeground(new java.awt.Color(255, 255, 255));
        cashLbl.setText("Cash DH :");

        balanceLBl.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        balanceLBl.setForeground(new java.awt.Color(255, 255, 255));
        balanceLBl.setText("Balance DH :");

        lblRetour.setBackground(new java.awt.Color(0, 0, 0));
        lblRetour.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblRetour.setForeground(new java.awt.Color(255, 255, 255));
        lblRetour.setText("00");

        btnPrint.setBackground(new java.awt.Color(0, 0, 0));
        btnPrint.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnPay.setBackground(new java.awt.Color(0, 0, 0));
        btnPay.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalLbl)
                    .addComponent(balanceLBl)
                    .addComponent(cashLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLbl)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashLbl)
                    .addComponent(edtCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceLBl)
                    .addComponent(lblRetour))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        splitter.setLeftComponent(jPanel2);

        pnlMain.add(splitter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pnlBottom.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlBottom.setPreferredSize(new java.awt.Dimension(1178, 80));

        btnClose1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnClose1.setText("Close");
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });

        lblTable1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblTable1.setText("Table");
        lblTable1.setOpaque(true);

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose1)
                    .addComponent(lblTable1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBottom, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible( false );
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnClearProductsFromTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearProductsFromTableActionPerformed
            if ( productModel.isEmpty() ) {
                return ;
           }
        productModel.resetQuantity();
        productModel.empty();
        lblTotal.setText( "00.00" );
    }//GEN-LAST:event_btnClearProductsFromTableActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed

        try {
            double tot = Double.valueOf(lblTotal.getText());
            double paid = Double.valueOf( edtCash.getText());
            if ( paid < tot ) {
                error("Please adapt your Paid amount.");
                edtCash.requestFocusInWindow();
                edtCash.selectAll();
                return ;
            }
            double balance = paid - tot ;
            
            DecimalFormat df = new DecimalFormat("00.00") ;
            
            lblRetour.setText(String.valueOf(df.format(balance)));
            
            productModel.saveToFile( this.title );
        } catch (IOException ex) {
            error(ex.getMessage() );
        }
        
    }//GEN-LAST:event_btnPayActionPerformed

    private void catListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_catListValueChanged
        Category cat = catList.getSelectedValue();
        pnlCategoryProducts.removeAll();
        
        cat.forEach( p -> {
            ProductButton pb = new ProductButton(p);
            pb.addActionListener( new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        addProduct(pb.getProduct());
                    } catch (CloneNotSupportedException ex) {
                        Logger.getLogger(TableContentDialog.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } );
            pnlCategoryProducts.add( pb );
        } );
        
        pnlCategoryProducts.revalidate();
        pnlCategoryProducts.repaint();
        
    }//GEN-LAST:event_catListValueChanged

    private void btnIncByOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncByOneActionPerformed
        if ( productModel.isEmpty() ) {
            return ;
        }
        int row = productTable.getSelectedRow();
        if ( row == -1 ) {
            error("Please Select a Row in the Table." );
            return ;
        }
        String productId = productModel.getValueAt( row, 0 ).toString();
        Product product = productModel.getProductByID(Integer.valueOf( productId ));
        product.incByOne();
        productModel.fireTableDataChanged();
        calcTotal();
        if ( !productModel.products().isEmpty() ) {
            productTable.setRowSelectionInterval( row, row);
        }
    }//GEN-LAST:event_btnIncByOneActionPerformed

    private void btnDecByOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecByOneActionPerformed
        if ( productModel.isEmpty() ) {
            return ;
        }
        int row = productTable.getSelectedRow();
        if ( row == -1 ) {
            error("Please Select a Row in the Table." );
            return ;
        }
        String productId = productModel.getValueAt( row, 0 ).toString();
        Product product = productModel.getProductByID(Integer.valueOf( productId ));
        
        if ( product.getQtn() == 1 ) {
            productModel.remove(row);
        }
        
        product.decrementByOne();
        productModel.fireTableDataChanged();
        
        if ( product.getQtn()>=1 ) {
                productTable.setRowSelectionInterval( row, row);
        }
        
        calcTotal();
    }//GEN-LAST:event_btnDecByOneActionPerformed

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
        NewCategoryDialog.get(this).up();
    }//GEN-LAST:event_btnAddCategoryActionPerformed

    public void addProduct( Product product ) throws CloneNotSupportedException{
        if ( productModel.products().isEmpty() ) {
            this.productModel.add( product );
        } else {
            Product prod = productModel.getProductByID( product.id );
            if ( null == prod ) {
                this.productModel.add( product );
            } else{
                prod.incByOne();
            }
            this.productModel.fireTableDataChanged();
        }
        
        calcTotal();
    }

    private void calcTotal() {
       double tot =   this.productModel.products().stream().mapToDouble( Product::getPriceWithQtn ).sum();
       tot = (float) (Math.round(tot * 100) / 100.0);
       final DecimalFormat df = new DecimalFormat("00.00") ;
       lblTotal.setText( df.format( tot ) );
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceLBl;
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnClearProductsFromTable;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnDecByOne;
    private javax.swing.JButton btnIncByOne;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel cashLbl;
    private javax.swing.JList<Category> catList;
    private javax.swing.JTextField edtCash;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblRetour;
    private javax.swing.JLabel lblTable;
    private javax.swing.JLabel lblTable1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlCategories;
    private javax.swing.JPanel pnlCategoryProducts;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlProducts;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable productTable;
    private javax.swing.JSplitPane splitter;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables

    private void error(String message) {
        JOptionPane.showMessageDialog(this, message, "Error Message!", JOptionPane.ERROR_MESSAGE);
    }

}
