package net.slidesoft.wavesbistro.dialogs;

import java.util.Objects;
import javax.swing.JDialog;
import net.slidesoft.wavesbistro.AddCatListener;
import net.slidesoft.wavesbistro.Utils;

/**
 *
 * @author Rachid El Alaoui , SlideSoft.net
 */
public final class NewCategoryDialog extends javax.swing.JDialog {

    private static NewCategoryDialog dlg;
    private AddCatListener addCatListener;
    
    /**
     * Creates new form NewCategoryDialog
     */
    private NewCategoryDialog(java.awt.Frame parent) {
        super(parent, "Add New Category", true);
        initComponents();
    }
    private NewCategoryDialog(java.awt.Dialog parent) {
        super(parent, "Add New Category", true);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public static NewCategoryDialog get( JDialog parent ) {
        if ( Objects.isNull(dlg) ) {
            dlg = new NewCategoryDialog( parent );
        }
        return dlg ;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCatName = new javax.swing.JLabel();
        edtCatName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnClose = new javax.swing.JButton();
        btnAddCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCatName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCatName.setText("Category Name");

        edtCatName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnAddCat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddCat.setText("Add");
        btnAddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCat)
                            .addGap(18, 18, 18)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCatName)
                                .addComponent(edtCatName, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddCat, btnClose});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCatName)
                .addGap(8, 8, 8)
                .addComponent(edtCatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCat)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible( false );
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatActionPerformed
        String cat = edtCatName.getText().trim();
        if ( cat.isEmpty() ) {
            return ;
        }
        if ( cat.trim().length()<4 ) {
            Utils.info( "At least 3 characters for the Category Name", null );
            return ;
        }
        addCatListener.add( cat );
    }//GEN-LAST:event_btnAddCatActionPerformed

    public void setAddCategoryListener(AddCatListener addCatListener) {
        this.addCatListener = addCatListener;
    }

    public void up() {
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCat;
    private javax.swing.JButton btnClose;
    private javax.swing.JTextField edtCatName;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCatName;
    // End of variables declaration//GEN-END:variables
}
